variables:
  AWS_REGION: ap-southeast-1
  CONJUR_APPLIANCE_URL: "https://apj-secrets.secretsmgr.cyberark.cloud/api"
  CONJUR_ACCOUNT: "conjur"
  CONJUR_AUTHN_JWT_SERVICE_ID: "jtan-gitlab"
  CONJUR_AUTHN_JWT_TOKEN: "${CI_JOB_JWT_V2}"
Fetch variables from Conjur:
  stage: .pre
  image:
    name: docker.io/cyberark/authn-jwt-gitlab:alpine-1.0.0
  script:
    - echo AWS_ACCESS_KEY_ID=$(CONJUR_SECRET_ID="data/vault/jtan/Cloud Service-aws-access-keys-jtan-jtan-cjc/AWSAccessKeyID" /authn-jwt-gitlab) >> conjurVariables.env
    - echo AWS_SECRET_ACCESS_KEY=$(CONJUR_SECRET_ID="data/vault/jtan/Cloud Service-aws-access-keys-jtan-jtan-cjc/password" /authn-jwt-gitlab) >> conjurVariables.env
  artifacts:
    reports:
      dotenv: conjurVariables.env
Run Terraform using variables from Conjur:
  stage: deploy
  image:
    name: docker.io/hashicorp/terraform:latest
    entrypoint: [""]
  before_script:
    - terraform init
  script:
    - terraform apply -auto-approve
